package com.asia.frete.relatoriodefretev03;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class principal implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private com.asia.frete.relatoriodefretev03.roteiro principal_roteiro;
   private com.asia.frete.relatoriodefretev03.containers principal_containers;
   private com.asia.frete.relatoriodefretev03.pedido principal_pedido;
   private java.lang.String principal_link_erp;

   private java.math.BigDecimal principal_total;

   private java.util.List<com.asia.frete.relatoriodefretev03.item> principal_item;

   private java.util.List<com.asia.frete.relatoriodefretev03.cliente> principal_cliente;

   public principal()
   {
   }

   public com.asia.frete.relatoriodefretev03.roteiro getPrincipal_roteiro()
   {
      return this.principal_roteiro;
   }

   public void setPrincipal_roteiro(
         com.asia.frete.relatoriodefretev03.roteiro principal_roteiro)
   {
      this.principal_roteiro = principal_roteiro;
   }

   public com.asia.frete.relatoriodefretev03.containers getPrincipal_containers()
   {
      return this.principal_containers;
   }

   public void setPrincipal_containers(
         com.asia.frete.relatoriodefretev03.containers principal_containers)
   {
      this.principal_containers = principal_containers;
   }

   public com.asia.frete.relatoriodefretev03.pedido getPrincipal_pedido()
   {
      return this.principal_pedido;
   }

   public void setPrincipal_pedido(
         com.asia.frete.relatoriodefretev03.pedido principal_pedido)
   {
      this.principal_pedido = principal_pedido;
   }

   public java.lang.String getPrincipal_link_erp()
   {
      return this.principal_link_erp;
   }

   public void setPrincipal_link_erp(java.lang.String principal_link_erp)
   {
      this.principal_link_erp = principal_link_erp;
   }

   public java.math.BigDecimal getPrincipal_total()
   {
      return this.principal_total;
   }

   public void setPrincipal_total(java.math.BigDecimal principal_total)
   {
      this.principal_total = principal_total;
   }

   public java.util.List<com.asia.frete.relatoriodefretev03.item> getPrincipal_item()
   {
      return this.principal_item;
   }

   public void setPrincipal_item(
         java.util.List<com.asia.frete.relatoriodefretev03.item> principal_item)
   {
      this.principal_item = principal_item;
   }

   public java.util.List<com.asia.frete.relatoriodefretev03.cliente> getPrincipal_cliente()
   {
      return this.principal_cliente;
   }

   public void setPrincipal_cliente(
         java.util.List<com.asia.frete.relatoriodefretev03.cliente> principal_cliente)
   {
      this.principal_cliente = principal_cliente;
   }

   public principal(
         com.asia.frete.relatoriodefretev03.roteiro principal_roteiro,
         com.asia.frete.relatoriodefretev03.containers principal_containers,
         com.asia.frete.relatoriodefretev03.pedido principal_pedido,
         java.lang.String principal_link_erp,
         java.math.BigDecimal principal_total,
         java.util.List<com.asia.frete.relatoriodefretev03.item> principal_item,
         java.util.List<com.asia.frete.relatoriodefretev03.cliente> principal_cliente)
   {
      this.principal_roteiro = principal_roteiro;
      this.principal_containers = principal_containers;
      this.principal_pedido = principal_pedido;
      this.principal_link_erp = principal_link_erp;
      this.principal_total = principal_total;
      this.principal_item = principal_item;
      this.principal_cliente = principal_cliente;
   }

}