package com.asia.frete.relatoriodefretev03;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class roteiro implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String tipo_operacao;

   public roteiro()
   {
   }

   public java.lang.String getTipo_operacao()
   {
      return this.tipo_operacao;
   }

   public void setTipo_operacao(java.lang.String tipo_operacao)
   {
      this.tipo_operacao = tipo_operacao;
   }

   public roteiro(java.lang.String tipo_operacao)
   {
      this.tipo_operacao = tipo_operacao;
   }

}